# -*- coding: utf-8 -*-
"""Parcial 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gBnG8AI_sYkvnosuiD5O_rKzlIxIGdE
"""

from textblob import TextBlob
import requests
from bs4 import BeautifulSoup
import pandas as pd
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
spanishStopWords = stopwords.words('english')
import matplotlib.pyplot as plt
import seaborn as sns

url = 'http://books.toscrape.com/catalogue/category/books/romance_8/page-1.html'
allBooks = []

for page in range(1):
  response = requests.get(f'{url}?page={page}')

  if response.status_code != 200:
    print(f'Error en {page}')
    continue

  soup = BeautifulSoup(response.content, 'html.parser')
  books = soup.find_all('li', class_='col-xs-6 col-sm-4 col-md-3 col-lg-3')

  for book in books:
    title = book.find('h3').find('a')['title']
    price = book.find('p', class_='price_color').text
    allBooks.append({
        'title': title,
        'price': price
    })

for book in allBooks:
    print(f"Title: {book['title']}\nPrice: {book['price']}\n")

dfBooks = pd.DataFrame(allBooks)
dfBooks.to_csv("books.csv")

import requests
from bs4 import BeautifulSoup

url = 'http://books.toscrape.com/catalogue/black-dust_976/index.html'
response = requests.get(url)

if response.status_code != 200:
    print("Error")

soup = BeautifulSoup(response.content, 'html.parser')

descriptionHeader = soup.find('h2', string='Product Description')

if descriptionHeader:
    description = descriptionHeader.find_next('p').text
    print(description)
else:
    print("Description not found.")