# -*- coding: utf-8 -*-
"""práctica1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htriUvjMb4Cc3CmTQPG3kmw6XAtrP6TD
"""

from textblob import TextBlob
import requests
from bs4 import BeautifulSoup
import pandas as pd
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

spanishStopWords = stopwords.words('english')
import matplotlib.pyplot as plt
import seaborn as sns

url = 'http://quotes.toscrape.com/'
maxPages = 50 // 10 + 1
allReviews = []

for page in range(1, maxPages + 1):
  response = requests.get(f'{url}?page={page}')

  if response.status_code != 200:
    print(f'Error en {page}')

    continue
  soup = BeautifulSoup(response.content, 'html.parser')

  reviewContainers = soup.find_all('div', class_ = 'quote')

  for container in reviewContainers:
    reviewText = container.find('span', {'class':'text'}).text.strip()

    authorElement = container.find('span', {'itemprop':'author'})
    if authorElement:
      reviewAuthor = authorElement.text.strip()
    else:
      reviewAuthor = None

    review = {
        'text': reviewText,
        'author': reviewAuthor
    }

    allReviews.append(review)

for index, review in enumerate(allReviews, 1):
  print(f"Review {index}: {review['text']} - {review['author']}\n")

reviewsText = """
Review 1: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

Review 2: “It is our choices, Harry, that show what we truly are, far more than our abilities.”

Review 3: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

Review 4: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

Review 5: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

Review 6: “Try not to become a man of success. Rather become a man of value.”

Review 7: “It is better to be hated for what you are than to be loved for what you are not.”

Review 8: “I have not failed. I've just found 10,000 ways that won't work.”

Review 9: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”

Review 10: “A day without sunshine is like, you know, night.”

Review 11: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

Review 12: “It is our choices, Harry, that show what we truly are, far more than our abilities.”

Review 13: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

Review 14: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

Review 15: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

Review 16: “Try not to become a man of success. Rather become a man of value.”

Review 17: “It is better to be hated for what you are than to be loved for what you are not.”

Review 18: “I have not failed. I've just found 10,000 ways that won't work.”

Review 19: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”

Review 20: “A day without sunshine is like, you know, night.”

Review 21: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

Review 22: “It is our choices, Harry, that show what we truly are, far more than our abilities.”

Review 23: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

Review 24: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

Review 25: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

Review 26: “Try not to become a man of success. Rather become a man of value.”

Review 27: “It is better to be hated for what you are than to be loved for what you are not.”

Review 28: “I have not failed. I've just found 10,000 ways that won't work.”

Review 29: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”

Review 30: “A day without sunshine is like, you know, night.”

Review 31: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

Review 32: “It is our choices, Harry, that show what we truly are, far more than our abilities.”

Review 33: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

Review 34: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

Review 35: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

Review 36: “Try not to become a man of success. Rather become a man of value.”

Review 37: “It is better to be hated for what you are than to be loved for what you are not.”

Review 38: “I have not failed. I've just found 10,000 ways that won't work.”

Review 39: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”

Review 40: “A day without sunshine is like, you know, night.”

Review 41: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

Review 42: “It is our choices, Harry, that show what we truly are, far more than our abilities.”

Review 43: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

Review 44: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

Review 45: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

Review 46: “Try not to become a man of success. Rather become a man of value.”

Review 47: “It is better to be hated for what you are than to be loved for what you are not.”

Review 48: “I have not failed. I've just found 10,000 ways that won't work.”

Review 49: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”

Review 50: “A day without sunshine is like, you know, night.”

Review 51: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

Review 52: “It is our choices, Harry, that show what we truly are, far more than our abilities.”

Review 53: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

Review 54: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”

Review 55: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”

Review 56: “Try not to become a man of success. Rather become a man of value.”

Review 57: “It is better to be hated for what you are than to be loved for what you are not.”

Review 58: “I have not failed. I've just found 10,000 ways that won't work.”

Review 59: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”

Review 60: “A day without sunshine is like, you know, night.”
"""

reviewsList = [review.split(': ', 1)[1] for review in reviewsText.split('Review ')[1:]]
df = pd.DataFrame(reviewsList, columns = ['Review'])
print(df)

from wordcloud import WordCloud, STOPWORDS
text = ''.join(review for review in df['Review'])
words = text.split()
positiveWords = [word for word in words if TextBlob(word).sentiment.polarity > 0.5]
filteredText = ''.join(positiveWords)

wordCloud = WordCloud(stopwords = STOPWORDS, background_color = 'white', width = 800, height = 600).generate(filteredText)

plt.figure(figsize = (8, 6))
plt.imshow(wordCloud, interpolation = 'bilinear')
plt.axis('off')
plt.show

negativeWords = [word for word in words if TextBlob(word).sentiment.polarity > -0.5]
filteredTextNeg = ''.join(negativeWords)

wordCloudNeg = WordCloud(stopwords = STOPWORDS, background_color = 'white', width = 800, height = 600).generate(filteredTextNeg)

plt.figure(figsize = (8, 6))
plt.imshow(wordCloudNeg, interpolation = 'bilinear')
plt.axis('off')
plt.show

def categorizeSentiment(polarity):
    '''Categoriza el sentimiento basado en la polaridad'''
    if polarity > 0.5:
        return 1
    else:
        return -1

# Calcular la polaridad de cada reseña
df['polarity'] = df['Review'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Categorizar el sentimiento basado en la polaridad
df['sentiment'] = df['polarity'].apply(categorizeSentiment)
df.drop('polarity', axis=1, inplace=True)
pd.set_option("display.max_rows", None)
df

import plotly.express as px

# Cambiando los valores de la columna 'sentiment' a 'negative' y 'positive'
df['sentiment'] = df['sentiment'].replace({-1 : 'negative', 1 : 'positive'})

# Creando el histograma
fig = px.histogram(df, x="sentiment")
fig.update_traces(marker_color="indianred",marker_line_color='rgb(8,48,107)',marker_line_width=1.5)
fig.update_layout(title_text='Product Sentiment')
fig.show()