# -*- coding: utf-8 -*-
"""RNconvulucionalesTareaPt1(aves).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQzVUlshhL31_YfRUb_5-MFYdPv16FdF
"""

from google.colab import files
uploaded = files.upload()

!pip install kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# De la url del dataset se obtiene el nombre del programador y el nombre del dataset "gpiosenka/100-bird-species"
!kaggle datasets download -d gpiosenka/100-bird-species

# Descomprimir el archivo
!unzip 100-bird-species.zip

import matplotlib.pyplot as plt
from PIL import Image

# Obtener las imagenes
imgRoute = '/content/train/ALBATROSS/001.jpg'

# Abrir imagen
img = Image.open(imgRoute)

# Mostrar imagen
plt.imshow(img)
plt.axis('off')
plt.show()

!ls /content/train/ALBATROSS | head -5

# Graficar las imagenes
imgs5 = [
  '001.jpg',
  '002.jpg',
  '003.jpg',
  '004.jpg',
  '005.jpg'
]
plt.figure(figsize = (15, 3))

for i, img5 in enumerate(imgs5):
  imgRoute = f'/content/train/ALBATROSS/{img5}'
  img = Image.open(imgRoute)

  # Configuración de subplot
  plt.subplot(1, 5, i + 1)
  plt.imshow(img)
  plt.axis("off")
  plt.title(img5)

plt.tight_layout()
plt.show()