# -*- coding: utf-8 -*-
"""rottenTomatoesWebScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-BHBoPDBLwG0I1quQPEtGRbPLRYMxNv
"""

from textblob import TextBlob
import requests
from bs4 import BeautifulSoup
import pandas as pd
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

englishStopWords = stopwords.words('english')
import matplotlib.pyplot as plt
import seaborn as sns

# Inicio del scrapping
url = 'https://www.marca.com/resultados/futbol/r-madrid/estadisticas/2023/0101/C186.html'
maxPages = 360 // 20 + 1
allReviews = []

for page in range(1, maxPages + 1):
  response = requests.get(f'{url}?page={page}')

  if response.status_code != 200:
    print(f'Error en {page}')

    continue

  soup = BeautifulSoup(response.content, 'html.parser')

  reviewContainers = soup.find_all('div', class_ = 'review-text-container')

  for container in reviewContainers:
    reviewText = container.find('p', {'data-qa':'review-quote'}).text.strip()
    reviewDate = container.find('span', {'data-qa':'review-date'}).text.strip()
    reviewLinkTag = container.find('a', class_ = 'full-url')
    reviewLink = reviewLinkTag['href'] if reviewLinkTag else None

    # Extraer los datos
    review = {
        'text': reviewText,
        'date': reviewDate,
        'link': reviewLink
    }

    allReviews.append(review)

for index, review in enumerate(allReviews, 1):
  print(f"Review {index}: {review['text']}\n")

reviewsText = """
Review 1: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 2: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 3: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 4: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 5: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 6: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 7: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 8: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 9: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 10: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 11: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 12: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 13: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 14: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 15: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 16: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 17: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 18: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 19: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 20: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 21: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 22: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 23: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 24: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 25: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 26: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 27: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 28: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 29: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 30: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 31: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 32: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 33: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 34: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 35: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 36: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 37: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 38: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 39: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 40: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 41: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 42: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 43: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 44: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 45: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 46: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 47: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 48: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 49: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 50: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 51: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 52: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 53: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 54: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 55: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 56: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 57: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 58: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 59: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 60: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 61: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 62: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 63: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 64: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 65: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 66: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 67: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 68: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 69: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 70: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 71: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 72: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 73: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 74: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 75: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 76: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 77: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 78: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 79: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 80: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 81: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 82: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 83: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 84: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 85: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 86: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 87: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 88: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 89: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 90: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 91: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 92: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 93: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 94: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 95: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 96: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 97: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 98: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 99: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 100: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 101: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 102: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 103: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 104: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 105: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 106: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 107: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 108: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 109: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 110: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 111: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 112: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 113: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 114: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 115: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 116: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 117: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 118: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 119: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 120: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 121: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 122: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 123: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 124: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 125: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 126: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 127: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 128: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 129: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 130: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 131: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 132: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 133: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 134: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 135: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 136: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 137: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 138: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 139: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 140: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 141: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 142: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 143: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 144: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 145: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 146: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 147: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 148: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 149: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 150: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 151: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 152: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 153: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 154: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 155: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 156: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 157: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 158: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 159: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 160: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 161: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 162: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 163: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 164: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 165: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 166: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 167: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 168: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 169: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 170: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 171: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 172: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 173: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 174: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 175: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 176: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 177: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 178: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 179: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 180: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 181: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 182: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 183: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 184: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 185: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 186: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 187: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 188: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 189: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 190: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 191: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 192: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 193: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 194: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 195: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 196: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 197: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 198: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 199: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 200: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 201: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 202: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 203: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 204: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 205: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 206: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 207: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 208: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 209: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 210: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 211: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 212: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 213: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 214: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 215: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 216: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 217: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 218: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 219: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 220: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 221: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 222: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 223: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 224: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 225: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 226: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 227: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 228: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 229: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 230: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 231: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 232: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 233: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 234: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 235: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 236: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 237: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 238: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 239: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 240: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 241: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 242: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 243: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 244: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 245: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 246: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 247: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 248: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 249: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 250: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 251: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 252: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 253: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 254: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 255: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 256: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 257: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 258: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 259: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 260: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 261: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 262: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 263: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 264: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 265: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 266: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 267: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 268: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 269: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 270: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 271: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 272: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 273: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 274: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 275: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 276: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 277: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 278: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 279: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 280: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 281: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 282: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 283: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 284: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 285: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 286: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 287: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 288: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 289: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 290: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 291: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 292: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 293: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 294: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 295: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 296: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 297: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 298: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 299: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 300: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 301: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 302: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 303: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 304: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 305: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 306: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 307: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 308: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 309: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 310: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 311: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 312: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 313: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 314: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 315: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 316: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 317: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 318: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 319: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 320: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 321: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 322: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 323: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 324: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 325: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 326: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 327: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 328: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 329: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 330: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 331: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 332: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 333: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 334: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 335: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 336: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 337: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 338: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 339: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 340: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 341: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 342: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 343: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 344: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 345: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 346: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 347: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 348: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 349: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 350: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 351: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 352: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 353: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 354: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 355: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 356: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 357: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 358: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 359: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 360: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.

Review 361: Consider the lousy animation and awkward performances and highly questionable narrative and ask what, to the tune of “Under the Sea,” the hell is this?

Review 362: To begin, Halle Bailey. Remember her name and don’t forget it. From the trailers, to the red carpet, under the sea and above it, she is charismatic, humble, and a songstress.

Review 363: By making a series of small changes and using his experience in adapting musicals ("Chicago"/"Into the Woods"), [director Rob] Marshall crafts a story we know and gives it an entirely different vibe, for better or worse.

Review 364: Halle Bailey is by far the best part of Rob Marshall’s 2023 live action movie. She is a luminous talent with an angelic voice. She is without a doubt Ariel with her wide-eyed wonder and teen rebellion.

Review 365: Another popcorn summer film, this time inviting a dive into the cool CGI waters of Atlantica peppered with shark attacks, shipwrecks and a giant octopus sea witch. Empty calories definitely, but fun all the same

Review 366: All the film’s flaws and miscalculations can be forgiven by its most impressive saving grace: Bailey’s performance is as remarkable as it is enchanting.

Review 367: ...looks like a cheapie commercial for Royal Caribbean Cruises.

Review 368: [Bailey] is absolutely magnetic on the screen and it’s hard to imagine many others being as perfect for the role as she turns out to be.

Review 369: The casting, new songs and overall look aren’t strong enough to promote or weak enough to disparage.

Review 370: It’s a weird message to be sending children these days: pretend to be something you’re not, keep your trap shut and hope nobody notices the scales.

Review 371: Nothing in recent memory feels so much like amalgamated groupthink capital-C Content like this Little Mermaid.

Review 372: The Little Mermaid enriches virtually every narrative aspect compared to the original, deepening Ariel and Eric's arcs while exploring the same core themes without losing any of its predecessor's essence.

Review 373: The Little Mermaid (2023) is the most successful of the live-action Disney remakes. Even with its shortcomings, the heart of the animated film exists within this new version which cannot be said for many other live action remakes.

Review 374: Mostly thanks to the music and dramatic performances from Bailey and McCarthy, "The Little Mermaid" goes along swimmingly. And that puts it several strokes ahead of other live-action Disney remakes.

Review 375: Although it does not possess the same campy nature as its animated predecessor, The Little Mermaid maintains the emotion of the beloved story through a star-creating performance and emphasis on relationships.

Review 376: I never saw the original [Disney's Little Mermaid], so I have no frame of reference and can't say if it's better or not. For me, this was a so-so movie...The songs are fun, but didn't have the magic or the heart that you'd expect from Disney.

Review 377: Halle Bailey was born to be a Disney Princess INCREDIBLE! The visuals were pretty solid and the songs were great. It’s not without It’s flaws and a bit too long but overall, I’m very excited for everyone to see Halle bring this classic princess to life.

Review 378: When 'Under the Sea' echoes against a literal sea of colour, movement, creatures and energy, it's a dazzling Golden Age Hollywood-esque spectacular. There's no escaping the movie's bloat when it's not merrily floating, however.

Review 379: It is hard to see too many fans of the original The Little Mermaid being disappointed in this adaption. The classic songs are there, and delivered in unique re-workings, with some extras also thrown in.

Review 380: The Little Mermaid is the perfect movie for newcomers to the story… for adults who love the original they may not feel the magic the same way. One thing everyone should agree on though is Halle Bailey's incredible performance.
"""

reviewsList = [review.split(': ', 1)[1] for review in reviewsText.split('Review ')[1:]]
df = pd.DataFrame(reviewsList, columns = ['Review'])
print(df)

from wordcloud import WordCloud, STOPWORDS
text = ''.join(review for review in df['Review'])
words = text.split()
positiveWords = [word for word in words if TextBlob(word).sentiment.polarity > 0.5]
filteredText = ''.join(positiveWords)

wordCloud = WordCloud(stopwords = STOPWORDS, background_color = 'white', width = 800, height = 600).generate(filteredText)

plt.figure(figsize = (8, 6))
plt.imshow(wordCloud, interpolation = 'bilinear')
plt.axis('off')
plt.show

negativeWords = [word for word in words if TextBlob(word).sentiment.polarity > -0.5]
filteredTextNeg = ''.join(negativeWords)

wordCloudNeg = WordCloud(stopwords = STOPWORDS, background_color = 'white', width = 800, height = 600).generate(filteredTextNeg)

plt.figure(figsize = (8, 6))
plt.imshow(wordCloudNeg, interpolation = 'bilinear')
plt.axis('off')
plt.show

def categorizeSentiment(polarity):
    '''Categoriza el sentimiento basado en la polaridad'''
    if polarity > 0.5:
        return 1
    else:
        return -1

# Calcular la polaridad de cada reseña
df['polarity'] = df['Review'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Categorizar el sentimiento basado en la polaridad
df['sentiment'] = df['polarity'].apply(categorizeSentiment)
df.drop('polarity', axis=1, inplace=True)
pd.set_option("display.max_rows", None)
df

import plotly.express as px

# Cambiando los valores de la columna 'sentiment' a 'negative' y 'positive'
df['sentiment'] = df['sentiment'].replace({-1 : 'negative', 1 : 'positive'})

# Creando el histograma
fig = px.histogram(df, x="sentiment")
fig.update_traces(marker_color="indianred",marker_line_color='rgb(8,48,107)',marker_line_width=1.5)
fig.update_layout(title_text='Product Sentiment')
fig.show()