# -*- coding: utf-8 -*-
"""sentimiento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lj1iUlLxa_DzPYCKTlRLu-up2KYhr9TW
"""

!pip install transformers

!pip install timm

from transformers import pipeline

# Aplicar función de sentimiento
sentimiento = pipeline(task = "text-classification", model = "pysentimiento/robertuito-sentiment-analysis")

texto = ["Me encanta aprender inteligencia artificial",
         "Me molesta no tener una buena calificación en mi examen",
         "Es una buena pelicula, pero no me gustó",
         "Quiero ir al parque",
         "Me gusta mucho la pizza, es mi comida favorita"]
sentimiento(texto)