# -*- coding: utf-8 -*-
"""WebScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vl5rkPj3dc6jU50BYX24siL26hM6FC91
"""

import pandas as pd
from bs4 import BeautifulSoup
import requests

# URL de la página que contiene la lista de libros más vendidos
web = 'https://en.wikipedia.org/wiki/List_of_best-selling_books#List_of_best-selling_individual_books'

# Hacer el request para obtener el contenido de la página
respuesta = requests.get(web)
content = respuesta.text

# Parsear el contenido con Beautiful Soup
s = BeautifulSoup(content, 'lxml')

# Encuentra todas las tablas con la clase 'wikitable'
tables = s.findAll('table', {'class': 'wikitable'})

# Asegúrate de que hay al menos cuatro tablas antes de continuar
if len(tables) < 4:
    raise ValueError("No se encontraron suficientes tablas.")

# Junta las filas de las primeras cuatro tablas, excluyendo los encabezados
all_rows = []
for table in tables[:4]:
    all_rows.extend(table.findAll('tr')[1:])

# Listas para almacenar los datos extraídos
titles = []
authors = []
original_languages = []
pub_years = []
approx_sales = []
genres = []

for row in all_rows:
    cells = row.findAll('td')

    # Extraer información de cada celda
    title = cells[0].get_text(strip=True)
    author = cells[1].get_text(strip=True)
    original_language = cells[2].get_text(strip=True)
    pub_year = cells[3].get_text(strip=True)
    approx_sale = cells[4].get_text(strip=True)
    genre = cells[5].get_text(strip=True) if len(cells) > 5 else ""  # Algunas filas pueden no tener género

    # Agregar información a las listas
    titles.append(title)
    authors.append(author)
    original_languages.append(original_language)
    pub_years.append(pub_year)
    approx_sales.append(approx_sale)
    genres.append(genre)

# Crear DataFrame a partir de las listas
df_books = pd.DataFrame({
    'Libro': titles,
    'Autor': authors,
    'Lenguaje Original': original_languages,
    'Año de Publicación': pub_years,
    'Ventas Aproximadas': approx_sales,
    'Genero': genres
})

# Configuraciones para imprimir el DataFrame de forma ordenada
pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 10000)
pd.set_option('display.max_colwidth', 50)

# Imprimir solo las primeras 30 filas
print(df_books.head(30))

# Exportar DataFrame a CSV
df_books.to_csv("LibrosMasVendidos.csv", index=False)

















